### ISSUE TITLE
Name not Defined Error while cloning GDTOT files

### ISSUE THREAD

**Issue by AgentsofJARVIS** [vishnoe115/mltb-wiszky#1]
**Describe the bug**
Unable to clone GDTOT files

**To Reproduce**
1. Used this Command with this link or file. - /clone
2. Before/after/while Upload . - Before upload
3. Link used - https://new2.gdtot.sbs/file/37677252927
[log.txt](https://github.com/vishnoe115/mltb-wiszky/files/9413222/log.txt)

Log data attached

**Comment by vishnoe115** [comment]
> **Describe the bug** Unable to clone GDTOT files
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Used this Command with this link or file. - /clone
> 2. Before/after/while Upload . - Before upload
> 3. Link used - https://new2.gdtot.sbs/file/37677252927
>    [log.txt](https://github.com/vishnoe115/mltb-wiszky/files/9413222/log.txt)
> 
> Log data attached

from your log it's raise DirectDownloadLinkException("ERROR: Try in your broswer, mostly file not found or **user limit exceeded**!")
you have been reached limit, try using another account,, not bug.

it's working prove:
![image](https://user-images.githubusercontent.com/54537571/186362983-87427e46-82e7-4415-bd25-2d972e4394cf.png)
